export const PATH = {
  LAYOUT: "/",
  HOME: "",
  PROFILE: "/profile",
  LOGIN: "/login",
  REGISTER: "/register",
  MOVIE: "/phim/:slug",
  DATVE: "/datve/:id",
  TINTUC: "/news",
  HETHONGRAP: "/he-thong-rap",
  EVENTANDSALE: "/khuyen-mai-su-kien",
  LICHCHIEU: "/lich-chieu/",
  RAP: "/rap-phim/:mahethong",
  NOTFOUND: "*",
};
